### PR TITLE
Merge bug fixes and documentations

### PR DESCRIPTION
**Pull request by imda-lionelteo**
This PR resolves 2 issues that were reported; Issue https://github.com/aiverify-foundation/moonshot/issues/241 and https://github.com/aiverify-foundation/moonshot/issues/242.

### CODE REVIEW

**Comment by imda-benedictlee** [comment]
Hey @imda-lionelteo, can you help me add in the details for the changes made in this PR? Many thanks.

**Comment by imda-normanchia** [comment]
@imda-benedictlee this PR resolves 2 issues that was reported. which are issue  #241  and #242

for the #241 issue, it is a system incompatibility issue and we have no intention of coming up for a fix to accommodate older macbook models, hence the solution that we propose will be added to the documentation. 

for #242  there is an issue where the `.env` file will not be created if the user fails to install the requirement for moonshot-data. the change that was done is to create the `.env` file after the installation of moonshot-data before installing the requirements.

**Review by imda-benedictlee — APPROVED** [review]
Approved

**Comment by imda-benedictlee** [comment]
Venv File Created:
Screenshot 2024-06-30 at 6 42 09 PM

**Comment by imda-benedictlee** [comment]
The following benchmark test runs are working:
"ollama-llama3",
"azure-openai-gpt4-turbo-preview",
"openai-gpt35-turbo",
"openai-gpt4",
"openai-gpt35-turbo-16k"

Results Attached
[result.json](https://github.com/user-attachments/files/16044161/result.json)

**Comment by imda-benedictlee** [comment]
Automated Red Teaming is working with the following models:
"ollama-llama3",
"azure-openai-gpt4-turbo-preview",
"openai-gpt35-turbo",
"openai-gpt4",
"openai-gpt35-turbo-16k"

Screenshot 2024-06-30 at 8 11 47 PM

**Review by imda-normanchia — APPROVED** [review]

**Review by miyamaya9 — APPROVED** [review]

**Review by imda-kelvinkok — APPROVED** [review]

**Pull request merged**
