### PR TITLE
add total datasets property in cookbook response model

### PR DESCRIPTION
**Pull request by imda-amdlahir**
## Description

Adding total datasets in get cookbooks responses from web-api.

## Motivation and Context

web-ui has a new requirement to display number of datasets in cookbooks in a bunch of cookbooks overview screens

## Type of Change

- feat: A new feature

## How to Test

Spin up web-api and hit the GET cookbooks endpoint. 
Example response payload:
```[
    {
        "id": "legal-summarisation",
        "name": "Legal Summarisation",
        "description": "This cookbook runs general capabilitiy benchmark on legal summarisation model.",
        "recipes": [
            "analogical-similarity",
            "auto-categorisation",
            "cause-and-effect",
            "contextual-parametric-knowledge-conflicts",
            "gre-reading-comprehension",
            "squad-shifts-tnf"
        ],
        "total_prompt_in_cookbook": 66514,
        "total_dataset_in_cookbook": 6 // newly added in this PR
    }
] 
```

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [x]  I have tested the changes locally and verified that they work as expected.
- [ ]  I have added or updated the necessary documentation (README, API docs, etc.).
- [ ]  I have added appropriate unit tests or functional tests for the changes made.
- [x]  I have followed the project's coding conventions and style guidelines.
- [x]  I have rebased my branch onto the latest commit of the main branch.
- [ ]  I have squashed or reorganized my commits into logical units.
- [ ]  I have added any necessary dependencies or packages to the project's build configuration.
- [x]  I have performed a self-review of my own code.
- [x]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.

## Screenshots (if applicable)

[If the changes involve visual modifications, include screenshots or GIFs that demonstrate the changes.]

## Additional Notes

[Add any additional information or context that might be relevant to reviewers.]

<details>
  <summary>Developer Certificate of Origin</summary>

 ```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
 ```
</details>

### CODE REVIEW

**Review by imda-normanchia — APPROVED** [review]

**Comment by imda-benedictlee** [comment]
Jira Ticket: https://imda-dsl.atlassian.net/browse/MS-448?atlOrigin=eyJpIjoiMGYxNDBhN2NlMzMxNDM0ZDhjZWVkN2ZlM2M3NmY4OGIiLCJwIjoiaiJ9

**Review by imda-normanchia — APPROVED** [review]

**Review by imda-jacksonboey — APPROVED** [review]
tested by Benedict

**Comment by imda-jacksonboey** [comment]
Screenshot 2024-10-03 at 4 31 07 PM

**Comment by imda-jacksonboey** [comment]
Tested ok

**Pull request merged**
